# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  gcr: # Define access for a private registry
    type: docker-registry
    url: gcr.io
    username:
    password: 
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "every 1 minute"
    registry: "gcr.io/gcp-maas-prod/"
    labels:
      - "latest"
      - "dependencies"
      - "gcr-update"
    allow:
      - dependency-type: "docker"
        update-type: "version"
    open-pull-requests-limit: 10
    create-pr: true      # enable PR creation
    commit-message: "chore(deps): update solace image tags"
    automerge: false     # disable automatic merging of PRs
    strategy:
      merge:
        method: "squash"
